### ISSUE TITLE
JSDocs vs iron-doc-viewer

### ISSUE THREAD

**Issue by garcianavalon** [ageapps/polymer-style-guide#1]
Have you considered using [iron-doc-viewer](https://elements.polymer-project.org/elements/iron-doc-viewer) and ditching JSDocs?

In my opinion its a more polymeric approach, works great with tooling (`polymer init blank-element` will scaffold this comment plus the [iron-demo-helpers](https://elements.polymer-project.org/elements/iron-demo-helpers)), and promotes writing clean and readable code over documentation boilerplate.

**Comment by ageapps** [comment]
I totally agree with this.
I think it would be nice to mix this idea of documentations through another component and make a template with yeoman that uses [iron-doc-viewer](https://elements.polymer-project.org/elements/iron-doc-viewer) for showing the compoent´s API
